name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Minify
        uses: anthonyftwang/minify-action@v1.0.1

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: src
          path: |
            index.html
            error.html
            robots.txt
            *.png
            *.ico
            site.webmanifest
            assets/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: src

      - name: Upload to S3 (me)
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
            --exclude ".git\*"
            --exclude "README.md"
            --exclude "docker-compose.yml"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_ME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ME }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: '.'

      - name: Upload to S3 (net)
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
            --exclude ".git\*"
            --exclude "README.md"
            --exclude "docker-compose.yml"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_NET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_NET }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: '.'

      - name: Invalidate CloudFront Cache (me)
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CF_DISTRIBUTION_ME }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ME }}

      - name: Invalidate CloudFront Cache (net)
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CF_DISTRIBUTION_NET }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_NET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_NET }}
